# Setup
title: 'Recipes :fork_and_knife:'
baseurl: "/recipes"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.

email: lido@paglia.org
twitter_username: nicemarmot
github_username:  lidopaglia
instagram_username: lidopaglia

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
