# Setup
title:     ':fork_and_knife:'
baseurl:   ""

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout:   "post"

# Outputting
permalink:     pretty

# Conversion
markdown:    kramdown
kramdown:
  input: GFM
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# About/contact
author:
  name:       Lido Paglia
  url:        http://paglia.org
  instagram:  lidopaglia
  twitter:    nicemarmot

# Gems
gems:
  - jemoji
