# Setup
title: 'Recipes :fork_and_knife:'
baseurl: "/recipes"
description: "A collection of notes from experiments in my kitchen."

email: lido@paglia.org
twitter_username: nicemarmot
github_username:  lidopaglia
instagram_username: lidopaglia

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
